### ISSUE TITLE
Can I use custom fonts for the text on a chart?

### ISSUE THREAD

**Issue by vg-cad** [chartist-js/chartist#1020]
I am curious to know if I can stylize the fonts of the charts to use a custom font that I have installed on my site. I am using Wordpress.

**Comment by silsha** [comment]
You can change all parts of the chart by CSS. To use a custom font you can try:
```css
.ct-label {
    font-family: 'Exo 2';
}
```
