### ISSUE TITLE
inner section of donut sliced off when the last series item takes up more than half of the chart

### ISSUE THREAD

**Issue by zevdg** [chartist-js/chartist#1068]
reproduction link: https://codepen.io/zevdg/pen/qxXKZj

The easiest way to trigger this is to make a series with only 2 items where the 1st is smaller than the second.  I've illustrated it with more series items in the reproduction link

**Comment by gionkunz** [comment]
You're not using the default styles of chartist. The problem is that the chart should have fill: none;

```css
.ct-chart-donut{
  fill: none;
}
.ct-series-a {
	stroke: blue;
}
.ct-series-b {
	stroke: red;
}
.ct-series-c {
	stroke: green;
}
.ct-series-d {
	stroke: violet;
}
```
