### ISSUE TITLE
Labels in donut not in center of slice (offset Y) in Edge

### ISSUE THREAD

**Issue by petervtzand** [chartist-js/chartist#1199]
![Screenshot 2019-11-22 at 15 52 38](https://user-images.githubusercontent.com/1419427/69435910-b5f4aa80-0d40-11ea-98dc-e0e0ba8f911b.png)

As you can see the labels are not in the middle/center of the slice, it's a few pixels too high. In Chrome & Firefox I don't experience this. I have no idea what's causing this..

**Comment by petervtzand** [comment]
I looked at what goes wrong and I think it's the following:
The labels are centered with `dominant-baseline: center`, but this isn't supported by Edge.

As a workaround, I added to/overwote  the css of `ct-label`:
```css
.ct-chart svg.ct-chart-donut g .ct-label {
  font-size: 16px;
  dominant-baseline: no-change;  /* which is the default */
  transform: translate(0, 4px); /* 4px = 25% of font-size */
}
```
