### ISSUE TITLE
Colours of Bars in Bar graphs

### ISSUE THREAD

**Issue by meghaklp** [chartist-js/chartist#229]
Hi, I am experimenting with chartist and I had few questions:
1) Is there an easy way to make a stacked horizontal bar chart?
2) Can bar charts have tool tips?
3) Can each bar in a single series bar chart have a different colour (hypothetically)
4) How can I over-ride the default colour of a single series bar chart? How do I specify it in the options.

Any help? Maybe these are not issues but, just questions. Thanks.

**Comment by gionkunz** [comment]
1) yes. check http://gionkunz.github.io/chartist-js/examples.html#stacked-bar-chart
2) They can. However, tooltips should be developed on top of chartist. You can get an example of how to write tool tips in this article http://www.smashingmagazine.com/2014/12/16/chartist-js-open-source-library-responsive-charts/ . There is also an open issue for creating a tool tip plugin which I'm supporting (but have no time atm) #219 
3) Currently this is not possible but there is an open issue that tracks this: #209
4) You can get an example for this here: http://jsbin.com/kowida/2/edit?html,css,js,output

**Comment by meghaklp** [comment]
Thanks, this is very useful

**Comment by OscarGodson** [comment]
This is old but if other people came to it i just used CSS to color each bar and make repeating patterns. For example, if you had 4 colors you wanted to repeat you could use CSS like:

``` css
.ct-chart .ct-bar:nth-of-type(4n+1) {
  stroke: #71A28A;
}

.ct-chart .ct-bar:nth-of-type(4n+2) {
  stroke: #FF6414;
}

.ct-chart .ct-bar:nth-of-type(4n+3) {
  stroke: #EFB200;
}

.ct-chart .ct-bar:nth-of-type(4n+4) {
  stroke: #91A453;
}
```
