### ISSUE TITLE
Axis titles

### ISSUE THREAD

**Issue by dsbudiac** [chartist-js/chartist#27]
Occasionally, it's not apparent what a given axis/labels is/are referring to. Axis titles help to bring context.

I was hoping to handle axis titles myself outside the chartist.js by using absolutely positioned psuedo elements. For example:

**HTML:**

``` html
 <div class="ct-chart" data-x-axis="My x-axis title" data-y-axis="My y-axis-title"></div>
```

**CSS:**

``` css
.ct-chart { position: relative; }

[data-x-axis]::before {
  content: attr(data-x-axis);
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  text-align: center;
}

[data-y-axis]::after {
  content: attr(data-y-axis);
  position: absolute;
  /* vertical text rotation stuff */
}
```

But that produces a few problems:
1. **Takes axis title elements out of normal flow**. In my example, axis titles are absolutely positioned. I could add a margin to the chart element, but that gets especially harry if the axis title needs to wrap to a second line
2. **Titles are never truly centered in relation to axis lines**. The labels add extra padding to the chart pane.
3. **Reliably positioning y-axis rotated text is a huge pain**... if not impossible. I can't seem to find a way to position the title reliably. Especially if the y-axis title needs to wrap to a second line.

My SVG text positioning knowledge is quite limited, but I would think this problem would be better handled in SVG over HTML/CSS.
