### ISSUE TITLE
Is there a option to add border to line chart

### ISSUE THREAD

**Issue by santosh1994** [chartist-js/chartist#339]

**Comment by santosh1994** [comment]
@gionkunz

**Comment by gionkunz** [comment]
Just add a border to your container:

``` css
.ct-chart {
  border: 1px solid black;
}
```
