### ISSUE TITLE
Styling labels

### ISSUE THREAD

**Issue by klaemo** [chartist-js/chartist#375]
Hey,
this is more of a question than an issue. I have a bar chart with `distributeSeries: true`, a lot of bars and rather wordy labels that overlap:
![labels-straight](https://cloud.githubusercontent.com/assets/778624/8477121/03ed32bc-20c8-11e5-8ffe-5db98c87a502.png)
You can see the problem :) So, I have tried rotating the labels:
![labels-rotated](https://cloud.githubusercontent.com/assets/778624/8477133/1e8be546-20c8-11e5-888b-81914aac5eaa.png)
Using this pattern I'd ideally want to force the labels to be one-line only and align perfectly with the bar. How can I achieve that?
I'm also open for different ideas about positioning the labels.

Thank you very much, for this module and your help.

**Comment by klaemo** [comment]
Solved it! Here's the code

``` js
chart.on('draw', (ctx) => {
      if (ctx.type === 'label') {
        // adjust label position for rotation
        const dX = ctx.width / 2 + (100 - ctx.width)
        ctx.element.attr({ x: ctx.element.attr('x') - dX })
      }
})
```

and

``` css
.ct-chart-bar .ct-label.ct-horizontal.ct-end {
  display: block;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  transform: rotate(-30deg);
  transform-origin: 100% 0;
  text-align: right;
  max-height: 1.5em;
  min-width: 100px;
  max-width: 100px;
}
```
