### ISSUE TITLE
Edit column width ? 

### ISSUE THREAD

**Issue by FabienPapet** [chartist-js/chartist#405]
How can I edit columns (a,b,c) width in a bar chart ? 
Didn't found it in the doc.

**Comment by OmeGak** [comment]
I'm new to Chartist and I was looking for the same. I would be expecting this to be an option to be passed to the chart, but instead, by looking at the examples, CSS seems the only way it can be achieved:

``` css
.your-chart .ct-bar {
    stroke-width: 60px
}
```
