### ISSUE TITLE
Font size can't be changed on charts

### ISSUE THREAD

**Issue by guillaume-g** [chartist-js/chartist#414]
Hi,

I have a simple problem but I can't find how to solve it...
I am trying to change the font size of labels for a chart but it doesn't work.

I know you can override the font-size with CSS but it just doesn't work for me.

Thank for this great tool, everything works well, it's my only problem!

Do you have any ideas?

**Comment by bartveneman** [comment]
Can you post an example of what you have tried? That could make it a little easier for others to determine what could be the problem.

**Comment by guillaume-g** [comment]
Hi,

This is the current chart:

![graphexample](https://cloud.githubusercontent.com/assets/7372595/9440788/c13f8b56-4a69-11e5-87fc-c20e56eaced6.png)

Here is the HTML Code:

``` html
<div class="ct-chart ct-perfect-fourth travel-times-estimation"></div>
```

Here is the CSS code for the class "travel-times-estimation":

``` css
.travel-times-estimation {
    width: 72%;
    height:80%;
    left: 20.2%;
    top: 12%;
    font-size: 3em;
}
```

Am I doing something wrong?

Thanks for your help!
