### ISSUE TITLE
Add an example to rotate labels with CSS

### ISSUE THREAD

**Issue by gionkunz** [chartist-js/chartist#420]

**Comment by glebm** [comment]
For a horizontal bar chart with non-`foreignObject` axis labels (which I prefer as they are faster and work better with mouse selection, search, etc):

```css
.ct-chart-bar.ct-horizontal-bars .ct-label.ct-horizontal.ct-end {
  transform: rotate(-30deg);
  transform-box: fill-box;
  transform-origin: 100% 0;
  text-anchor: end;
}
```
