### ISSUE TITLE
Center line chart labels at grid line

### ISSUE THREAD

**Issue by hansmaad** [chartist-js/chartist#439]
If we google for images of "line chart" we quickly see that almost all chart implementations center the axes labels at tick marks or grid line. Chartist does not. Lables are left aligned which can be confusing for longer labels. It's not clear if the label belongs to the left grid line, the right or the space between them. We should have an option to define the alignment or center labels by default.

![chart1](https://cloud.githubusercontent.com/assets/3396747/9728196/9d7e8c82-5606-11e5-8fb2-ecb0d8afc5c1.png)

**Comment by amsul** [comment]
+1

Just came across the need for this as well. Seems like there's no easy way about this with just CSS — unless if you have a fixed number of columns and the graph is not responsive.

**Comment by gionkunz** [comment]
Yeah, we need to be careful in changing the defaults in minor releases but in general I agree. 

The current best approach for this is to use the `draw` event to offset all labels -50% (in pixel of course) and then center the text with CSS.

**Comment by JosefWN** [comment]
Is there any CSS3-only solution, or do we have to use JavaScript for this regardless of browser?

I have solved it with an ugly hack for now:

``` JavaScript
this.chartist.on('draw', function(event) {
  if(event.type === 'label') {
    if(!options.horizontalBars && event.axis.units.pos === 'y') {
      event.element.attr({ y: event.y + event.height / 6.5 });
    } else if((options.horizontalBars == null || options.horizontalBars) && event.axis.units.pos === 'x') {
      event.element.attr({ x: event.x - event.width / 2 });
    }
  }
});
```

``` CSS
.ct-chart .ct-label.ct-horizontal {
  line-height: 1 !important;
  text-align: center !important;
  display: inline-block !important;
}
```

The y-axis offset is hard to determine however, it is certainly not event.height / 2.

**Comment by JosefWN** [comment]
Another issue is that the last label is not as wide as the others, even if I make room for the text using padding to the right, the auto-width of the label is wrong with this approach:
![screen shot 2015-10-19 at 16 56 39](https://cloud.githubusercontent.com/assets/12534742/10581377/9a4b6ba6-7682-11e5-8d89-30414ae9a871.png)

**Comment by mattcdavis1** [comment]
``` css
.ct-chart-bar.ct-horizontal-bars .ct-label.ct-horizontal.ct-end {
    display: inline-block;
    width: auto !important;
    transform: translateX(-50%);
}
```

![2016-08-27_15-08-10](https://cloud.githubusercontent.com/assets/403534/18029527/4f9614c6-6c68-11e6-978c-665129089359.png)
