### ISSUE TITLE
Styling scatter chart dots

### ISSUE THREAD

**Issue by JosefWN** [chartist-js/chartist#482]
I'm using the scatter chart superimposed on a plot background, looking to use both stroke and fill (for example white stroke, black fill), to ensure that regardless of background image, the dots will be clearly visible. Since the "dot" is a line, it's quite tricky (or do you guys know an easy css-only way?). Is there any rationale behind this decision? If it were a circle I would be able to style it easier.

**Comment by woble** [comment]
Fairly easy to accomplish. You have to replace the points with a circle and apply some custom styling.

``` css
.ct-point-circle {
    stroke-width: 2px;
    fill: white;
}

/* Apply different styling per serie */
.ct-series-a .ct-point-circle {
    stroke: tomato;
}

.ct-series-b .ct-point-circle {
    stroke: navy;
}
```

``` js
var circleRadius = 6;
chart.on('draw', function(data){
    if(data.type === 'point'){
        var circle = new Chartist.Svg('circle', {
            cx: data.x,
            cy: data.y,
            r: circleRadius,
            class: 'ct-point-circle'
        });

        data.element.replace(circle);
    }
});
```
