### ISSUE TITLE
Labels are off-screen when rotating (?)

### ISSUE THREAD

**Issue by andreasba** [chartist-js/chartist#574]
Good evening,

I have a pretty basic line chart where I have a lot of labels on the x-axis that is why I rotate them 45°. My CSS looks like the following:

``` CSS

/* For nice blueish line-charts */
.ct-series-a .ct-line,
.ct-series-a .ct-point {
    stroke: #337fcc;
}

/* We increase the font size of the chart axis */
.ct-label {
    font-size: inherit;
}

/* We rotate the label for the historical charts */
.ct-label.ct-horizontal.ct-end {
    /* Safari */
    -webkit-transform: rotate(-45deg);
    /* Firefox */
    -moz-transform: rotate(-45deg);
    /* IE */
    -ms-transform: rotate(-45deg);
    /* Opera */
    -o-transform: rotate(-45deg);
    /* Internet Explorer */
    filter: progid:DXImageTransform.Microsoft.BasicImage(rotation=2);
    white-space: nowrap;
}
```

Now when I have not lots of data points but only a few of them, for example like this

``` JSON
{"labels":["2016-01-02","2016-01-03"],"series":["41","41"]}
```

My graph looks like this in FF (current version):

![nolabels](https://cloud.githubusercontent.com/assets/15323226/12218868/8b52d6ee-b72c-11e5-82d8-3b09b8f0376e.JPG)

In Chrome I have labels but they are way off:

![chrome](https://cloud.githubusercontent.com/assets/15323226/12218871/95421fc0-b72c-11e5-9e6d-735c1f797df9.JPG)

My options set via JS look like this:

``` JS
                    var options = {
                        axisX: {
                            labelOffset: {
                                y: 35,
                                x: -45
                            }
                        },
                        axisY:{
                            onlyInteger: true
                        },
                        chartPadding: {
                            bottom: 40
                        },
                        plugins: [
                            Chartist.plugins.tooltip()
                        ]
                    };
                    // In adition to the regular options we specify responsive option overrides that will override the default configutation based on the matching media queries.
                    var responsiveOptions = [
                        ['screen and (min-width: 641px) and (max-width: 1024px)', {
                            showPoint: false,
                            axisX: {
                                labelInterpolationFnc: function(value) {
                                    // Will return mm-dd on medium screens
                                    return value.slice(5, 10);
                                }
                            }
                        }],
                        ['screen and (max-width: 640px)', {
                            showLine: false,
                            axisX: {
                                labelInterpolationFnc: function(value) {
                                    // Will return dd on small screens
                                    return value.slice(8, 10);
                                }
                            }
                        }]
                    ];
```

I need the label offset and the bottom padding due to the -45degree rotation as far as I can tell - at least thats how the chart looks fine if there is lots of data to show:

![lotsofdata](https://cloud.githubusercontent.com/assets/15323226/12218878/d3645f66-b72c-11e5-8a62-0149d989a944.JPG)

Any idea what could be the reason for this?

Thanks
Andreas
