### ISSUE TITLE
Pie Slice Border color for separators?

### ISSUE THREAD

**Issue by Devtr0n** [chartist-js/chartist#687]
I am trying to get spacing between the pie chart slices.
I am able to do this easily in Google Charts, by specifying a pieSliceBorderColor value.

How can I do this with chartist pie charts?

![piechart](https://cloud.githubusercontent.com/assets/2623606/14922581/0302730c-0dfe-11e6-8bcc-c0f05342c214.png)

By default, the chartist pie charts have no slice border. How can I add one?

**Comment by gionkunz** [comment]
Just use the styles:

``` css
.ct-slice-pie {
    stroke: white;
    stroke-width: 2px;
}
```
