### ISSUE TITLE
more colors for Pie Charts 

### ISSUE THREAD

**Issue by benelang** [chartist-js/chartist#79]
If you have a Pie Chart with more than 5 series the one above number 5 will all be in the same color so you can't see a difference any more.
![bildschirmfoto 2014-11-07 um 14 44 05](https://cloud.githubusercontent.com/assets/6049049/4953691/43ff510e-6684-11e4-9646-2437972c4e70.png)

Thank you very much for adding more colors.

**Comment by gionkunz** [comment]
Can you use the Sass version of the CSS? Its very easy to modify or add more colors there. I could also add more colors to the library but so far chartist only knows 4 colors :-)

**Comment by beefmaster** [comment]
i will attempt to fix do this in my fork, the dev has alot to do so ill try and help him out

**Comment by snickers54** [comment]
Hi, 
I'm going to use your library to display some gauge, but I'm surprised to not be able to add my custom colors via your API. Am I missing something ? I quickly understood I could add / change my colors into the CSS file. 
However, my main concern is to make a dynamic gauge which will change color depending on a value and thresholds. Why not let the user put something like this :  

``` js
new Chartist.Pie('.ct-chart', {
  series: [20, 10, 30, 40],
  colors:["#333", "#222", "#111", "#000"]
}, {
  donut: true,
  donutWidth: 60,
  startAngle: 270,
  total: 200,
  showLabel: false
});
```

**Comment by DSpeckhals** [comment]
@snickers54 You actually can customize the style for each series by passing the `data` parameter like this (using your example):

``` javascript
new Chartist.Pie('.ct-chart', {
  series: [{
      value: 20,
      className: "myclass1"
    },
    {
      value: 10,
      className: "myclass2"
    },
    {
      value: 30,
      className: "myclass3"
    },
    {
      value: 40,
      className: "myclass4"
    }]
}, {
  donut: true,
  donutWidth: 60,
  startAngle: 270,
  total: 200,
  showLabel: false
});
```

`className` represents a CSS class. You could then somewhere define a class:

``` css
.myclass1 {
  stroke: #333;
}
```

updated to reflect a [refactor](https://github.com/gionkunz/chartist-js/commit/85e4e37f4b63a71e471858ccbb582381f89abae8)

**Comment by gionkunz** [comment]
@snickers54 the reason why we don't add appearance relevant configuration to JavaScript is because our main goal is to keep a strong separation of concerns. I can understand this looks weird maybe unfamiliar in the first place as all other charting libraries support that, but it's part of the core philosophy of Chartist.js. If you'd like to color your chart based on thresholds I recommend you're using the draw events in Chartist.js. You could also develop a [Plugin](http://gionkunz.github.io/chartist-js/plugins.html) if you got time :-)

With a gauge chart this could look something like this: http://jsbin.com/pemute/1/edit?js,output

**Comment by snickers54** [comment]
thanks @DSpeckhals, but it's complex to dynamically generate css class from your DB. My colors are unknown until I get my data from the DB, and the number of threshold is also dynamic :) But thanks for this trick.

@gionkunz Ok, I get it, so I found a solution, as I'm working with angularJS and my Gauge is a directive, I directly edited the color into the DOM. It's maybe less classy, but i's working. 
Thanks for your exemple, but my need is to always display the triggers and see the value (with an arrow) change. Here a picture of what I did : ![Gauge](http://i59.tinypic.com/2mrtc7r.jpg)

It's working pretty well :) Thank you guys for your answers.

**Comment by DSpeckhals** [comment]
@snickers54 I was running into the same problem about dynamically generated styling. I ended up "cheating" a bit and adding an optional `data` field for color, then appending to or creating the style attribute for that stroke. However, like @gionkunz has suggested and shown in the example, I think I'm going to be aiming at capturing and handling the `draw` event instead. I like the separation of concerns.

By the way, is there any chance you could share your implementation like I see in your image? It looks great!

**Comment by gionkunz** [comment]
I'm closing this issue for now. Please reopen if needed.

**Comment by ilanbiala** [comment]
@gionkunz is there any way we can expand Chartist's color palette to ~8 colors? 4 is fine for line charts, but not for bar charts and pie charts where there are very frequently more than 4 pieces of data.

**Comment by gionkunz** [comment]
Just add more colors in your Sass settings file. If you import your own copy of the Sass settings file and change this line https://github.com/gionkunz/chartist-js/blob/develop/src/styles/settings/_chartist-settings.scss#L65 you can add as many colors as you like.

**Comment by ilanbiala** [comment]
@gionkunz it is nice that we can customize it, but what is the weight in adding 2-4 more colors?

**Comment by gionkunz** [comment]
Hey there. We already track this in the ticket #124 . I'll close this ticket now and we can track the creation of more colors in the default settings in the other ticket.

**Comment by gionkunz** [comment]
Sorry this ticket was already closed ;-)

**Comment by ilanbiala** [comment]
@gionkunz I thought that issue was somewhat related to functionality. I'll follow there.

**Comment by m-hcb** [comment]
here is the solution.. you just have to copy the relevant classes to your chart type from and apply your custom colors to that chart strokes. like I have done for donut.

``` CSS
.ct-chart .ct-series.ct-series-a .ct-slice.ct-donut {
        stroke: #002827
    }
    .ct-chart .ct-series.ct-series-b .ct-slice.ct-donut {
        stroke: #00382f
    }
    .ct-chart .ct-series.ct-series-c .ct-slice.ct-donut {
        stroke: #00591e
    }
    .ct-chart .ct-series.ct-series-d .ct-slice.ct-donut {
        stroke: #007f00
    }
    .ct-chart .ct-series.ct-series-e .ct-slice.ct-donut {
        stroke: #009900
    }
    .ct-chart .ct-series.ct-series-f .ct-slice.ct-donut {
        stroke: #00b200
    }
    .ct-chart .ct-series.ct-series-g .ct-slice.ct-donut {
        stroke: #51ce00
    }
    .ct-chart .ct-series.ct-series-h .ct-slice.ct-donut {
        stroke: #96ff00
    }
    .ct-chart .ct-series.ct-series-i .ct-slice.ct-donut {
        stroke: #ceff00
    } 
```

check this JSBin http://jsbin.com/cecaha/1/edit?css,output
