### ISSUE TITLE
Only 15 bars colors, no more...

### ISSUE THREAD

**Issue by abielmagudev** [chartist-js/chartist#844]
There not more bars graphics, only let 15 bars... test...

new Chartist.Bar('.ct-chart', {
    labels: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17'],
    series: [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170]

}, {
  distributeSeries: true
});

**Comment by metodribic** [comment]
There is only 15 predefined colors in ChartistJS and therefore you can't see 16th and higher bars. You need to define classes for those bars manually, like this : 

```css
.ct-series.ct-series-p {
        stroke: #00ffaa
}

.ct-series.ct-series-q {
        stroke: #00ffcc
}

.ct-series.ct-series-r {
        stroke: #00ffee
}

/* and so on... */
```

Check [#79](https://github.com/gionkunz/chartist-js/issues/79) or [#124](https://github.com/gionkunz/chartist-js/issues/124) for more informations about predefined colors. Check your updated example [here](http://jsbin.com/fivafuzaco/1/edit?css,js,output) .

Hope this helps! 😉
