### ISSUE TITLE
Rotating the x-axis labels

### ISSUE THREAD

**Issue by davebat** [chartist-js/chartist#845]
I have attempted to rotate the labels using CSS as per the examples already given 

https://jsbin.com/kezivew/edit?html,css,js,output

But in my example the labels are never visible.

**Comment by mtgibbs** [comment]
The simplest way to fix this would be to simply allow the SVG element inside being generated to overflow.

modified example:

https://jsbin.com/lemetexehu/edit?html,css,js,output

```css
#chart svg {
  overflow: visible;
}
```

**Comment by davebat** [comment]
Thankyou very much for your reply, this seems to help somewhat, but when I scroll down the x axis scrolls down as well. Please see example https://jsbin.com/rejocavica/edit?html,css,js,output

I've been playing and I set 

#chart svg {
  overflow: visible;
  transform: scaleX(1);
}

This means the x-axis is then fixed to the chart, rather than the page, as the chart has a transform other than none. Seems a bit hacky though and CSS isn't my strong suit.

If you don't mind I would appreciate if you could confirm if this approach is ok?

**Comment by mtgibbs** [comment]
Your labels are traveling down because you set their position fixed:

```css
.ct-label.ct-label.ct-horizontal {
  position: fixed;  /* THIS IS WHY */
  justify-content: flex-end;
  text-align: right;
  transform-origin: 100% 0;
  transform: translate(-100%) rotate(-45deg);
}
```

There is no need to do that.

Also, chartist has a padding parameter if you need some more space around your graph.

```js
var chart = new Chartist.Line('#chart', {
  chartPadding: {
    top: 20,
    bottom: 20,
    left: 20,
    right: 20
  },
  labels: ['How are you', 'Very long label', 3, 4, 5],
  series: [
    [10, 4, 12, 22, 21]
  ]
})
```
