### ISSUE TITLE
Apply selected colours on differents charts

### ISSUE THREAD

**Issue by ffradegrada** [chartist-js/chartist#881]
I know that in the getting started guide says that you don't want to mix javascript with css colouring. But, is there a way to configure differents colors for different charts?

I have two charts in the same page, and my client asked for having different colours between the charts, and I can't isolate one of another.

Thanks.

**Comment by Brobin** [comment]
I'd just give each chart a different class and assign the style like that

```html
<div class="chart-blue">
    ....
</div>
<div class="chart-red">
    ...
</div>
```

```css
.chart-red {
    color: red;
}
.chart-blue {
    color: blue;
}
```
